require 'sinatra/ysd_sinatra_booking'
require 'sinatra/ysd_sinatra_booking_management'
require 'sinatra/ysd_sinatra_booking_management_rest_api'
require 'ysd_plugin_booking_extension'
require 'ysd_plugin_booking_init'